VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "C_PROGRAMS"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public aNo               As Integer
Public aProjectName      As String
Public aProgramName      As String
Public aProgramDiv       As Integer
Public aProgramContent   As String
Public aCodeModule       As CodeModule
